{% set name = "basedmypy" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/basedmypy-{{ version }}.tar.gz
  sha256: 5a59d4b2b56d85c5ab22589b4bbb2eee4cc3a695c84e528c1b3b0335cccdf7e0

build:
  noarch: python
  entry_points:
    - mypy=mypy.__main__:console_entry
    - stubgen=mypy.stubgen:main
    - stubtest=mypy.stubtest:main
    - dmypy=mypy.dmypy.client:console_entry
    - mypyc=mypyc.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.2
    - wheel >=0.30.0
    - basedtyping >=0.0.3
    - typing_extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0
    - types-psutil
    - types-setuptools
    - pip
  run:
    - python >={{ python_min }}
    - basedtyping >=0.0.3
    - typing-extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0

test:
  imports:
    - mypy
  commands:
    - pip check
    - mypy --help
    - stubgen --help
    - stubtest --help
    - dmypy --help
    - mypy --version
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/KotlinIsland/basedmypy
  summary: Based static typing for Python
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - mypyc/external/googletest/LICENSE
    - mypy/typeshed/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - lucascolley
